In [1]:
import pyarrow.parquet as pq

table2 = pq.read_table('train-00000-of-00009.parquet')

table2.to_pandas()

              id                                               text
0              0  幼少期はよく高い位置で結んでいたが、最近はほとんど見ることはなかった。毛先を緩くまとめて横に...
1              1      鏡の中の桂から視線を外し、ゆっくり、ゆっくり、髪を梳いた。まるで何か、祈りを捧げるように。
2              2  いつも人んちで遠慮もなしに茶を啜ってるくせして随分と偉そうだなオイ、と思ったが、それよりも先...
3              3  銀時を押しやろうと腕を伸ばしてくるが、傷が痛むようでまともに力が入っていない。この状態で手足...
4              4  親や親戚などに頼れるのならばまだましですが、もう結婚していて、配偶者には秘密にしておきたい、...
...          ...                                                ...
2026863  2026863               カードキーで開錠し、ドアをひじと足で押して開け、部屋の中に入っていった。
2026864  2026864       夜な夜な黒い人影を目撃したという岩屋の話がありましたが、あれはいったい何なのでしょうか。
2026865  2026865  となると、後者で見るしかないですし、もちろん狙ったターゲットを確実に仕留める犯行を行っている...
2026866  2026866  つまり、犬との関係に於いてゼロ基点を保とうと心がける事は、「自己愛と犬への愛」のバランスを取...
2026867  2026867             ただ、自分と向き合う事を選択しても、しなくても、、誰も褒めも責めもしません。

[2026868 rows x 2 columns]